[build]
command = "pip install -r requirements.txt"

[env]
PYTHON_VERSION = "3.11"

[[redirects]]
from = "/docs"
to = "/api/docs"
status = 307

[[redirects]]
from = "/redoc"
to = "/api/redoc"
status = 307
